name: Deploy Next.js with Vanilla Extract to Azure Web App - nero-front

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ✅ 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ 2. 환경 변수 설정
      - name: Set Environment Variables
        run: |
          echo "NEXT_PUBLIC_CSRF_PROTECTION=${{ secrets.NEXT_PUBLIC_CSRF_PROTECTION }}" >> .env
          echo "NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }}" >> .env

      # ✅ 3. 이전 캐시 삭제
      - name: Clear Previous Cache
        run: |
          rm -rf node_modules .next

      # ✅ 4. Node_modules 캐싱 (속도 향상)
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # ✅ 5. 의존성 설치 (`npm install`로 dev 포함)
      - name: Install Dependencies
        run: npm install

      # ✅ 6. PATH에 `node_modules/.bin` 추가 (next 명령어 찾기)
      - name: Add node_modules/.bin to PATH
        run: echo "$PWD/node_modules/.bin" >> $GITHUB_PATH

      # ✅ 7. Next.js 빌드 (Vanilla Extract 포함)
      - name: Build Next.js
        run: npm run build

      # ✅ 8. `.next`, `.env` 포함하여 ZIP 생성
      - name: Create ZIP with .next and .env
        run: zip -r next.zip ./* .next .env -qr

      # ✅ 9. 빌드 파일 업로드
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: next.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # ✅ 1. 빌드된 앱 다운로드
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app

      # ✅ 2. Azure Web App에 배포
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'nero-front'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5E8997761B4F4CB89641E6137F16BD6D }}
          package: './next.zip'
